h2non/bimg

- resize_test.go
I believe the wrong image type was being used for the benchmark.  It didn't match the pattern of the other tests.
> Fixed the JPEG watermark benchmark.

- vips.h
There is several problems with libvips and bimg on Debian Jessie.
First one, as of today, libvips on Jessie is in version 7.40.6 (https://packages.debian.org/jessie/libvips38).
```
% go build
could not determine kind of name for C.vips_init
gcc errors for preamble:
In file included from ./vips.go:5:0:
vips.h: In function 'vips_rotate':
vips.h:67:15: error: 'VIPS_ANGLE_D0' undeclared (first use in this function)
int rotate = VIPS_ANGLE_D0;
^
vips.h:67:15: note: each undeclared identifier is reported only once for each function it appears in
vips.h:70:12: error: 'VIPS_ANGLE_D90' undeclared (first use in this function)
rotate = VIPS_ANGLE_D90;
^
vips.h:72:12: error: 'VIPS_ANGLE_D180' undeclared (first use in this function)
rotate = VIPS_ANGLE_D180;
^
vips.h:74:12: error: 'VIPS_ANGLE_D270' …
```
> Problem with building bimg on Debian Jessie

- options.go
- resize.go
- vips.go
- vips.h
Hi @h2non 
This is a PR to add support for Gaussian Blur.
As always, there's a big difference between < 7.41 and >= 7.42.
I've tested with 7.40, works great, but I cannot test right now with 7.42 (I'll try in a docker soon).
Quick information on the PR:
- Maybe the way I've added the options are not the best, let me know how exactly you want it
- before 7.42, only one parameter (radius int), after, two parameters (sigma, min_ampl double)
- I've plugged the call in the transformImage and shouldTransformImage, maybe you want it elsewhere
- I used the vips_gaussblur method, maybe using a mask is more effective ? that could be something to test
- No test/bench right now, but I'll add it later, just opening the PR to get a feedback on previous points
- No documentation yet, same as above, I'll …
> Gaussian Blur

- image_test.go
- options.go
- resize.go
- vips.go
- vips.h
Hello !
I was converting a transparent PNG to JPEG and realized than it was always outputting the image with a black background. I just moved away from ImageMagick to your library to be (way) more lightweight and that's the only feature I was missing. 
So I added a `Background` Option and check whether the input is PNG before using `vips_flatten`. 
I tested with vips 8.0.2, not really with prior versions. I also added a unit test for that function. 
I'm not sure I'm respecting your standard here so please let me know by comments if you want me to do any further modifications.
Cheers.
> Adding a Background option when flattening out a transparent PNG

- vips.go
Vips return an error (linear: vector must have 1 or 2 elements) if vips_flatten is called with an image that has no alpha channel. Therefore, the image should be checked before calling this function.
> Check for alpha channel before flattening image

- vips.go
When an image has an unsupported color space, vipsPreSave returns the pointer of the image passed to it unmodified. When this occurs, we must take care to not dereference the original image a second time; we may otherwise erroneously free the object twice
I ran into this issue when running tests with PNG's. The resize tests would fail with the results below
```
(bimg:25377): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `(null)'
SIGTRAP: trace trap
PC=0x7fcd5144ef9b m=4
signal arrived during cgo execution
goroutine 43 [syscall, locked to thread]:
runtime.cgocall(0x5c3d00, 0xc82045e3e8, 0xc800000000)
/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/cgocall.go:123 +0xc2 fp=0xc82045e398 sp=0xc82045e370 …
```
> Take care to not dereference the original image a second time

- History.md
- resize.go
- type.go
- version.go
- vips.go
- vips.h
- fix(#95): better image type inference and support check.
- fix(background): pass proper background RGB color for PNG image conversion.
- feat(types): validate supported image types by current `libvips` compilation.
- feat(types): consistent SVG image type checking.
- feat(api): add public functions `VipsIsTypeSupported()`, `IsImageTypeSupportedByVips()` and `IsSVGImage()`.
> Release 1.0.3

- .travis.yml
A first step to make the tests pass against older versions of libvips.
> Build against various libvips versions

- vips.go
- vips_test.go
When one tries to save as `MAGICK` it doesn't fail and uses the `jpeg` default output which doesn't follow the samurai way of failing early.
> Save as bimg.MAGICK

- .travis.yml
It downloads the tarball from the [official directory](http://www.vips.ecs.soton.ac.uk/supported/) where it's easier to pick a specific version (it seems).
> Running tests on more specific versions.

- .gitignore
- image.go
- image_test.go
- options.go
- resize.go
- resize_test.go
- vips.go
- vips.h
- vips_test.go
Hi!, 
This PR adds support for embedding images as watermarks. Like the example below.
It allows you to specify the Left and Top position and also the Opacity of the watermark.
```go
type WatermarkImage struct {
Left    int
Top     int
Buf     []byte
Opacity float32
}
```
Regards!
> Add support for image watermarks

- resize.go
- vips.go
- vips.h
- vips_test.go
I rewrote the image watermarking because of the related memory issue I had. See also #138. 
Few remarks:
- not sure what the specs are for watermarking, I took another approach to watermark an image with another image. Could be that it is not according the specs.
- ~~when running the test (on OSX) I get an error regarding defering a C-pointer:~~
- I run some benchmarks already available see the differences below.
Benchmarks (ran on OSX, local machine):
```
// New implementation
BenchmarkWatermarkJpeg-4        	      20	  60215874 ns/op
BenchmarkWatermarPng-4          	     500	   3406345 ns/op
BenchmarkWatermarWebp-4         	      30	  40243090 ns/op
BenchmarkWatermarkImageJpeg-4   	      20	  72954939 ns/op
BenchmarkWatermarImagePng-4     	      30	  38325610 ns/op …
```
> Fix for memory issue when watermarking images

- vips.go
Expose vips memory management functions for situations where the user wants to limit the memory usage or directly clean up allocated memory.
> Expose vips cache memory management functions.

- image.go
- image_test.go
In the spirit of this issue: https://github.com/h2non/imaginary/pull/140
Let offer a nice way to figure out the size of the buffer.
> Add Image.Length

- .travis.yml
As of today, the libvips website is down. :crying_cat_face: 
> Testing using libvips8.4.6 from Github.

- options.go
- resize.go
- vips.go
- vips.h
Set an bimg.Options OutputICC to an absolute path to the desired output ICC profile. If an embedded ICC profile is found in VipsImage, it is converted to the output ICC profile.
Fixes #50
Please let me know what you think about this.
/cc @tback
> Add option to convert embedded ICC profiles

- resize.go
- vips.go
- vips.h
I'm scaling an image down by about half and it seems bimg is using vips_affine to do the downscaling, which results in really aliased images:
Instead I've swapped it to use vips_reduce when downscaling:
I think this would fix https://github.com/h2non/bimg/issues/94
> Use vips reduce when downscaling

- vips.go
- vips.h
- it addresses the comments for ab4ef56bab7ca2f283b61a69f5bdf6784f1baadf
> Fix typo and small cleanup.

- vips.go
With #168 I've introduced a memory leak when `vips_icc_transform` was used (when `OutputICC` option was defined).
> Fix memory leak on icc_transform

- image_test.go
- options.go
- resizer.go
- vips.go
- vips.h
The trim function in libvips accepts optional parameters Background and Threshold, which can be quite important when trimming an image. The background is used to choose the color to actually trim away, and threshold is the amount of difference allowed, see [here](https://github.com/jcupitt/libvips/blob/f6db350a1e56e258e0a4e6ad6ee33b730b93b1c5/libvips/arithmetic/find_trim.c#L239-L274)
This should add those parameters, directly from the Options struct just as other such parameters.
One extra thing to add would be to have an option to detect the color to be used from ie. the top left pixel, to work with previously unknown images. This is also a feature I need.
> Add the option to use background and threshold options on trim

- options.go
- resizer.go
- vips.go
- vips.h
Surfacing option to save webp images in lossless mode.
Looking at libvips this param has been available for quite some time ([7.38 I think](https://github.com/jcupitt/libvips/blob/7.38/libvips/foreign/webpsave.c#L61)) so didn't wrap it in a version conditional.
Just testing the water but if this looks ok I could have a go at surfacing some of the other webp options mentioned in #135 like 
- `o.NearLossless`
- `o.AlphaQuality`
- `o.SmartSubsample` 
and potentially
- `o.WebpPreset` enum
Let me know if that's ok, along with the naming, and I can give it a shot.
> Add lossless option for saving webp

- preinstall.sh
The libvips release repo seems have changed to `https://github.com/libvips/libvips/` cause preinstall.sh broken, so I changed the tarbal url.
And I also updated the vips version to `v8.6.5`,  since the latest `v8.7.x` will produce error #244
> The preinstall.sh is out of date

- resizer.go
> Fix AreaWidth calculation

- README.md
- image.go
- metadata.go
- options.go
- vips.go
Libvips' documentation has largely moved to Github. Update various links throughout `README.md` and code comments.
> Libvips documentation URL and README copy updates

- vips.h
The vips_pngsave_bridge function uses the VIPS_FOREIGN_PNG_FILTER_NONE filter, which creates a 30% larger image. After switching to the VIPS_FOREIGN_PNG_FILTER_ALL filter, the file size is the same as for files created with another tool.
The default of the 'vipsthumbnail' utility is also the VIPS_FOREIGN_PNG_FILTER_ALL Filter.
Related issues: #221 and h2non/imaginary#237
> Reduce png size

- image.go
- metadata.go
- options.go
- vips.go
John Cupitt author of libvips moved repository to https://github.com/libvips/libvips. 
So links to the docs must be updated too.
Tnx
> Needs to update libvips documentation links

- resizer.go
- vips.go
- vips.h
**Orignal issue is** 
Having an extra border on the right and bottom side of images
**Root cause comes from**
https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-resize
> When upsizing (scale > 1), the operation uses vips_affine() with a VipsInterpolate selected depending on kernel . It will use VipsInterpolateBicubic for VIPS_KERNEL_CUBIC and above. It adds a 0.5 pixel displacement to the input pixels to get center convention scaling.
**The fix**
Enable vipsAffine to use `Extend` option value and send it to lipvips
This will change the default from the one that libvips use which is `background` to the ones that bimg use which is  `C.VIPS_EXTEND_BLACK`
But because the lip add extra 1 or .5 pixel the background is considered black anyway so this will not affect anyone …
> enable vipsAffine to use  `Extend` option value and send it to lipvips

- vips.h
Adding background to images with alpha channel are failing with error `linear: vector must have 1 or 4 elements`.
Code, that reproduce the issue:
```
package main
import (
"./bimg"
"fmt"
"io/ioutil"
"log"
"path"
)
func main() {
files, err := ioutil.ReadDir("./images")
if err != nil {
log.Fatal(err)
}
for _, f := range files {
data, err := ioutil.ReadFile(path.Join("./images", f.Name()))
if err != nil {
panic(err)
}
res, err := resize(data)
if err != nil {
panic(err)
fmt.Printf("Image resize error: %s, file: %s\n", err, f.Name())
}
ioutil.WriteFile(path.Join("./res", f.Name()), res, 0644)
}
}
func resize(data []byte) ([]byte, error) {
image := bimg.NewImage(data)
options := bimg.Options{
Width:         300,
Height:        300,
Quality:       90,
Interpolator:  bimg.Bicubic,
StripMetadata: …
```
> Fix bug with images with alpha channel on embeding background

- vips.go
Otherwise we manipulate potentially deallocated memory.
On some distributions things go fine for some reason, but
on others the memory actually gets deallocated and garbage is used,
leading to a segmentation fault in vips_image_guess_interpretation
> unref the image *after* we used it

- vips.go
- vips_test.go
This PR fixes runtime error  `slice bounds out of range [:-1]` when reading Exif metadata if Exif tag value contains " (" and starts with "(".
> Panic on reading Exif

- resizer.go
This will fix blurry images if the input is in webp format and the output is relativly small in his dimensions. This will fix issues #220, #339 makes #222 obsolet. This will also fix https://github.com/h2non/imaginary/issues/240.
The underlying issue is, that the `factor` comming out from `supportsShrinkOnLoad` is too high. `transformImage` has then a too large `shrink` and the image gets blurred.
I have no good idea, how to put that in a unit test, since the image output may differ on plattforms.
I did some manual testing with a lot of different output resolutions and compared the old with the new code. All blurring is gone.
`shrinkOnload` uses for WEBP now the same logic as for JPEG.
> Fix for blurry images from WEBP input and small output dimensions

- options.go
- resizer.go
- vips.go
- vips.h
@h2non FYI - the value of effort param in libvips for png_buffer is 1-10.
> allow effort param for png encoding when palette is true

- image_test.go
- type_test.go
- vips.go
- vips.h
This PR adds the support to save GIF images via the `vips_gifsave_buffer` function added in libvips 8.12
> Add GIF save support from libvips 8.12

- vips.h
A recent commit added new params to `vips_pngsave_bridge` (#398). However, as far as I can tell, the `effort` param is only available starting on libvips 8.12, effectively breaking PNG output for anyone stuck on older versions of the library.
This PR restores the ability of saving PNG files for users on older libvips versions, while still preserving the new features when libvips 8.12+ is available.
Fixes #401
> Support PNG output on older libvips versions

- vips.go
- vips.h
When libvips 8.13 is built with the `--disable-deprecated` flag, bimg doesn't build anymore because of errors like
```
In file included from ./vips.h:5,
from vendor/github.com/h2non/bimg/vips.go:5:
/thumbs/include/vips/vips7compat.h:682:1: error: unknown type name 'DOUBLEMASK'
682 | DOUBLEMASK *im_stats( VipsImage *in );
| ^~~~~~~~~~
/thumbs/include/vips/vips7compat.h:684:1: error: unknown type name 'DOUBLEMASK'
684 | DOUBLEMASK *im_measure_area( VipsImage *im,
| ^~~~~~~~~~
```
Since `im__print_all` is the only function being used from `vips7compat.h`, this shouldn't be an issue.
See https://github.com/libvips/libvips/blob/master/libvips/include/vips/vips7compat.h#L296
> Remove dependency on vips7compat

- image.go
Trivial PR, simply addresses a typo in the documentation of the `Colourspace` function.
> Fix a typo in Colourspace documentation

- options.go
- resizer.go
- vips.go
- vips.h
Adds [Kernel](https://www.libvips.org/API/current/libvips-resample.html#VipsKernel) in bimg.Option.
Uses the kernel param in vips_reduce https://www.libvips.org/API/current/libvips-resample.html#vips-reduce
Tries to solve https://github.com/h2non/bimg/issues/428
> Expose resampling kernel param in vips_reduce
