h2non/bimg

- options.go
- resize.go
- resize_test.go
- vips.go
- vips.h
Here's a set of changes for exposing sharp as suggested in:
https://github.com/h2non/bimg/issues/64
> Added interface and test for sharpen

- resize.go
- resize_test.go
> Auto-width and height calculations now round instead of floor.

- image_test.go
- resize.go
> Fix: Crop is doing resize. Closes #128

- .travis.yml
Adding go 1.8 and using the container environment (`sudo: false`) for the build.
Cheers,
> Enabled go 1.8 builds.

- image_test.go
It's probably my fault ;-)
ps: there is a warning: https://github.com/jcupitt/libvips/issues/632
> Fix tests where minor/major were mixed up

- resize.go
- vips.go
- vips.h
- vips_test.go
> Revert "Fix for memory issue when watermarking images"

- .travis.yml
I'm not super happy about the many tests but it seems to work.
> Download latest version of libvips from github.

- preinstall.sh
Added fresh Linux Mint distros in preinstall.sh
> Added Linux Mint 17.3+ distro names

- .travis.yml
> Update libvips to 8.5.5.

- image.go
- image_test.go
- options.go
- resize.go
- resize_test.go
As per https://github.com/h2non/imaginary/pull/136
> Replacing SmartCrop with a Gravity option

- .travis.yml
> Run libvips 8.5.6 on Travis.

- README.md
The resize is 800x600 and the checking was 400x300 after resizing.
> Fix Resize verification value

- vips.go
- vips_test.go
> Check the length before jumping into buffer.

- .travis.yml
> Add libvips 8.6 pre-release

- .travis.yml
> Update to libvips 8.5.8

- .travis.yml
> Update 8.6 to alpha4.

- resizer_test.go
Uniformise the Webp/WebP and Watermark/Watermark in the benchmarks.
> Small typos

- resize.go
- resize_legacy.go
per https://golang.org/pkg/go/build/#hdr-Build_Constraints
> fix build tag

- options.go
Add nearest-neighbour interpolation value
> Add nearest-neighbour interpolation

- resizer.go
Also makes it possible to do flip and flop (not just one).
> Fixes #225 by correcting the flip and flop directions

- preinstall.sh
- vips.go
- vips.h
Make it compatible with the latest vips. Fixes #255
> Make it compatible with the latest vips. Fixes #255

- resizer.go
> Fix image crop during embed

- resizer.go
- resizer_test.go
Adding the test mentioned in #250. However, since it wasn't committed there, I'm adding it here.
> Adding a test case that verifies #250

- image.go
- options.go
- resizer.go
- vips.go
- vips.h
Hello @h2non,
I'd like to work on this issue (https://github.com/h2non/bimg/issues/270).
Could you please give me any advice on my PR?
**how to use**
ex. buf, err = bimg.NewImage(buf).Gamma(0.454545)
> Gamma filter support

- preinstall.sh
Loki is based off Ubuntu Xenial and this worked fine on my machine.
> Adds support to Elementary OS Loki to preinstall.sh

- options.go
- resizer.go
- vips.go
- vips.h
Support for input ICC profile when there is none embeded in image.
> Update Transform ICC Profiles with Input Profile

- vips.go
- vips.h
Add vips_vector_set_enabled
(It helps me for that problem https://github.com/h2non/bimg/issues/267)
> Add vips_vector_set_enabled

- options.go
- vips.go
https://github.com/h2non/bimg/issues/404 
> I would like a way to change MaxSize by myself.
Added getter and setter to allow you to change maxSize yourself.
> Implement getter and setter for MaxSize

- options.go
- resizer.go
- vips.go
- vips.h
Hello. I needed support for brightness and contrast. So I decided to add it to bimg. I hope I did everything right.
> Support brightness and contrast
